# Generated by Django 5.1.1 on 2024-09-13 08:02

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='venue owner'),
        ),
        migrations.AlterField(
            model_name='event',
            name='manager',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=100, verbose_name='manager'),
        ),
    ]
