# Generated by Django 5.1.1 on 2024-09-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_event_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='approval',
            field=models.BooleanField(default=False, verbose_name='Approved'),
        ),
    ]
